CREATE TABLE FOODORDER (
OrderID INT NOT NULL,
Description VARCHAR(60) NOT NULL,
DiningStatus VARCHAR(60) NOT NULL,
UserID INT NOT NULL,
CONSTRAINT OrderPK PRIMARY KEY (OrderID),
CONSTRAINT UserPK FOREIGN KEY (UserID)
REFERENCES ACCOUNT (UserID)
);

